"""Add going_place to gate_passes

Revision ID: 0a3ad664c2b7
Revises: make_actual_return_date_nullable
Create Date: 2025-10-02 21:23:19.282495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a3ad664c2b7'
down_revision = 'make_actual_return_date_nullable'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gate_passes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('going_place', sa.String(length=255), nullable=False, server_default=''))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gate_passes', schema=None) as batch_op:
        batch_op.drop_column('going_place')

    # ### end Alembic commands ###
