"""add admin role to userrole enum

Revision ID: 0f9f0c9f0509
Revises: dcf277fbe3a2
Create Date: 2026-06-01 12:37:53.873905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f9f0c9f0509'
down_revision: Union[str, Sequence[str], None] = 'dcf277fbe3a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
