"""create users and gate_passes tables

Revision ID: ab75b41bfa1b
Revises: 
Create Date: 2026-05-23 13:51:55.052649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab75b41bfa1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('user_type', sa.Enum('student', 'warden', 'security', name='userrole'), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('room', sa.String(length=20), nullable=True),
    sa.Column('course', sa.String(length=100), nullable=True),
    sa.Column('year', sa.String(length=20), nullable=True),
    sa.Column('guardian_name', sa.String(length=100), nullable=True),
    sa.Column('guardian_phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('gate_passes',
    sa.Column('pass_id', sa.String(length=36), nullable=False),
    sa.Column('pass_number', sa.String(length=20), nullable=True),
    sa.Column('daily_serial', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('going_place', sa.String(length=255), nullable=False),
    sa.Column('out_date', sa.Date(), nullable=False),
    sa.Column('out_time', sa.Time(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('return_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Approved', 'Rejected', name='gatepassstatus'), nullable=False),
    sa.Column('approved_by_id', sa.String(length=20), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('exit_status', sa.Enum('In', 'Out', name='exitstatus'), nullable=False),
    sa.Column('actual_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_return_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_return_date', sa.Date(), nullable=True),
    sa.Column('security_remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('pass_id'),
    sa.UniqueConstraint('pass_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gate_passes')
    op.drop_table('users')
    # ### end Alembic commands ###
